# .github/workflows/makefile-workflow.yml
name: Run Makefile Targets

on:
  push:
    branches:
      - "**"  # Trigger on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Change as needed

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Run install
        run: make install

      - name: Run format
        run: make format

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test
